include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    constant_identifier_names: false
    use_build_context_synchronously: false
    prefer_relative_imports: true
    depend_on_referenced_packages: false
    library_prefixes: false
